# Site settings
title: BPJ Capital
email: contato@blpcrypto.com.br
description: >-
  BPJ Capital is an investment firm focused exclusively on ventures, tokens, and projects related to blockchain tech, digital currency, and crypto assets.
url: "https://blpcrypto.com.br"
baseurl: ""

# Build settings
permalink: pretty

collections:
  pages:
    output: true
    permalink: "/:name/"

markdown: kramdown
plugins:
  - jekyll-sitemap
